# Generated by Django 4.2.16 on 2024-10-12 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='authors_pics')),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('floor', models.IntegerField()),
                ('square', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(default='default.jpg', upload_to='exposition_pics')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='museum.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(default='default.jpg', upload_to='exhibit_pics')),
                ('date_of_creation', models.DateField()),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='museum.author')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='museum.employee')),
                ('exposition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='museum.exposition')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='museum.form')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date_time', models.DateTimeField()),
                ('image', models.ImageField(default='default.jpg', upload_to='exhibit_pics')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='museum.employee')),
                ('exposition', models.ManyToManyField(to='museum.exposition')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='museum.employeepost'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
