# Generated by Django 4.2.16 on 2024-10-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='museum.author'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='museum.exposition'),
        ),
    ]
