# Generated by Django 4.2.16 on 2024-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_author_date_of_birth_alter_author_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
