# Generated by Django 4.2.16 on 2024-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_exhibit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='date_of_creation',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='year_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
