# Generated by Django 4.2.16 on 2024-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_remove_exhibit_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='year_of_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
