# Generated by Django 4.2.16 on 2024-10-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_alter_exhibit_year_of_creation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormOfArt',
        ),
    ]
